### ISSUE TITLE
gost should be able to run without MQTT server

### ISSUE THREAD

**Issue by justb4** [Geodan/gost#88]
In issue #85 we finally concluded that lockup also occurred when no MQTT service was running.
But our config had disabled MQTT via `config.yaml`:

```
mqtt:
    enabled: false
    host: localhost
    port: 1883
```

Looks like [the code](https://github.com/Geodan/gost/blob/master/src/sensorthings/api/observation.go#L163) does not reflect this. At least I think `gost` should be able to run without MQTT so possibly a check on an 'MQTT-disabled' setting to skip the MQTT Publish step.
